language: python
python:
- '3.6'
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: cudmore
  password:
    secure: uE0cxtAqChkoFRHeOZZ0XDxeJnZPiFGD+UqcyXSDRmozM39JAHfywkslTj+6un458eoBFuYoq4IFgrTYkqIIZmAFGRv/Ek2+HuGaG3wKkG1tYuGrf4XmVrJIUkpzUpvrkazXxgtouCQdWZadPocMynKRR7JE32KvFzJjCuPFrnxilIoM2nbLI7iGfFyBT8j2l/BXFdT9jTiiFrDtN3Wz3+fRu7uiQMwy2LdV0QAJ2TijAYDX40q0P9Z4L2AwzGip3uvJDnNLVAZjeoRLAFk5CLKMfzf3RfMrCIrTwrbyXbEtokDDCsskXIVzCvd2ft+92I88rTbjLToZGePYP0kkvDjDTeJhgRoaxTt4YLOze+CUIqXw4nRXziSrrZSxGlA5Rl1CWxYzmeCrIr4zvEZvoSz+bSsI0OKFGb4uALGw5oN1H5fvxYL9QJyQhJXRsO9ESaMgEUDHG3eZsSC6Bh98mhyyJ/6BjpzYlxuNYdP2UkgzZ3ScdWGIBUb1XwbbyWFB9YSby8e8ZG7GqXvXdMiQhdqYWQfE22H+eekr9KMHnNmBDOvDChNCMtoM1zN+IbnS0+9ADmcvSGObfc7byZeUgZxVkWrcmYXqQ0mSE/HpSrYcWWxPE4VYo5YBm5Jsil6MZHeV3c6SxQoUFL3ispMllZ6RKjyxF/ykPCIMPJtc5Z8=
  on:
    tags: true

