site_name: PyMapManager

theme:
  name: 'material'
  #name: 'readthedocs'
  #name: 'mkdocs'

repo_url: http://github.com/cudmore/PyMapManager

pages:
    - Home: index.md
    - Install PyMapManager: install-pymapmanager.md
    - Install client/server: install-client-server.md
    - REST API: rest-api.md
    - Release Notes: release-notes.md